version: '3.8'
services:
  # app:
  #   image: oven/bun:latest
  #   container_name: readcomm_app
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["bun", "run", "src/index.ts"]
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/readcomm

  db:
    image: postgres:14
    container_name: readcomm_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: readcomm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: readcomm_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db

volumes:
  pgdata:
